### ISSUE TITLE
提个小意见

### ISSUE THREAD

**Issue by xhzengAIB** [SatanWoo/BuTaiMeng#1]
@SatanWoo 
如果能在tableView滚动停止的时候，自动滚动在放大的一个Cell，这样体验会好一点

Jack

**Comment by SatanWoo** [comment]
@xhzengAIB ??
我这个项目里没有用TableView啊

**Comment by xhzengAIB** [comment]
哈哈！  好吧！我写错项目了

**Comment by xhzengAIB** [comment]
这个项目非常好，你一直维护下去吗？

**Comment by SatanWoo** [comment]
@xhzengAIB 
会，暂时不会大更新，最近有点忙，有空就做完整

**Comment by xhzengAIB** [comment]
好的！继续star
